require 'rubygems'
require 'sinatra'
require 'net/http'
require 'uri'
require 'nokogiri'
require 'json'
require File.dirname(__FILE__) + '/../lib/cifra-club.rb' 
require File.dirname(__FILE__) + '/../lib/utils/extend_string.rb'